---
title: 'Preprocessing of scRNA-seq'
date: "12/05/2019"
output: html_document
---

Preprocessing the Etv2 scRNA-seq data using Seurat 3.1

```{r}
devtools::load_all('packages/compbio')
dataset <- 'dataset=Etv2scRNAseq_version=20190416a'
se <- readRDS(sprintf('%s/filtered.rds', dataset_dir(dataset)))
se <- se[rowSums(assays(se)$counts > 0) >= 3, ]
devtools::load_all('packages/compbio'); se <- scrublet(se, colData(se)$group, expected_doublet_rate = 0.1, min_counts = 2, min_cells = 3, min_gene_variability_pctl = 85, n_prin_comps = 30L)
is_doublet <- colData(se)$doublet_scores > 0.25
se <- se[, !is_doublet]

ns <- 4000	# number of HVG's
se_file <- sprintf('%s/filtered_nfeatures=%d.rds', dataset_dir(dataset), ns)
se2 <- seurat_preprocess(se, nfeatures = ns)
flog.info(sprintf('writing %s', se_file))
saveRDS(se2, se_file)
```

[2019-12-03] scVI analysis of the scRNA-seq of Etv2 induction 
followed by UMAP visualization

```{r}
devtools::load_all('packages/compbio')
library(umap)
dataset <- 'dataset=Etv2scRNAseq_version=20190416a'
ns <- 4000; latent <- 40
se_file <- sprintf('%s/filtered_nfeatures=%d.rds', dataset_dir(dataset), ns)
n <- rowData(se)$is_hvg
se2 <- scvi(se[n, ], n_latent = latent)
colData(se)$latent <- colData(se2)$latent
set.seed(1); y <- umap(colData(se)$latent)$layout
colData(se)$umap <- y
se_file <- sprintf('%s/filtered_nfeatures=%d_latent=%d.rds', dataset_dir(dataset), ns, latent)
saveRDS(se, se_file)
```


[2019-12-05] Cell clustering using louvain clustering
```{r}
devtools::load_all('packages/compbio')
dataset <- 'dataset=Etv2scRNAseq_version=20190416a'
nfeature <- 4000; latent_dim <- 40
se_file <- sprintf('%s/filtered_nfeatures=%d_latent=%d.rds', dataset_dir(dataset), nfeature, latent_dim)
se <- readRDS(se_file)

library(igraph)
library(FNN)
library(slingshot)
k <- 50	# knn neighbors
group2bg <- c(
	'MEF_Dox_D1' = 'black',
	'MEF_NoDox' = 'blue',
	'MEF_Dox_D2' = 'purple',
	'MEF_Dox_D7a' = 'red',
	'MEF_Dox_D7b' = 'pink'
)
knn <- get.knn(colData(se)$umap, k = k)
knn <- data.frame(from = rep(1:nrow(knn$nn.index), k), to = as.vector(knn$nn.index), weight = 1 / (1 + knn$nn.dist^2))
g <- graph_from_data_frame(knn, directed = FALSE)
g <- simplify(g)
lc <- cluster_louvain(g)
clust <- as.numeric(as.factor(membership(lc)))
G_max <- max(unique(clust))
colData(se)$cluster <- clust

# --- cell cluster plot
dev.new(width = 5, height = 5); par(mar = c(2, 2, 2, 2))
library(RColorBrewer); plot(colData(se)$umap, col = colorRampPalette(brewer.pal(11,'Spectral'))(G_max)[clust], pch = 16, asp = 1, xaxt = 'n', yaxt = 'n', main = 'cluster', xlab = '', ylab = '')
y_centers <- do.call('rbind', lapply(1:G_max, function(i) apply(colData(se)$umap[clust == i, ], 2, median)))
text(y_centers[, 1], y_centers[, 2], 1:G_max, cex = 1.25)

# --- MSP plot
dev.new(width = 5, height = 5); par(mar = c(2, 2, 2, 2))
set.seed(1); lin <- getLineages(colData(se)$umap, clust)
bg <- group2bg[colData(se)$group]
plot(colData(se)$umap, col = bg, asp = 1, pch = 16, xaxt = 'n', yaxt = 'n', main = 'Lineages', xlab = '', ylab = '', cex = 0.5)
lines(lin, lwd = 3, show.constraints = TRUE)
```

[2019-12-05] Get the smooth curve for each lineage
```{r}
devtools::load_all('packages/compbio')
dataset <- 'dataset=Etv2scRNAseq_version=20190416a'
nfeature <- 4000; latent_dim <- 40; k <- 50
set.seed(1); lin <- getLineages(colData(se)$umap, colData(se)$cluster)
set.seed(1); crv <- getCurves(lin, extend = 'n')  # this step ~ 30 mins
metadata(se)$curves <- crv
```

se_file <- sprintf('%s/filtered_nfeatures=%d_latent=%d_k=%d_slingshot.rds', dataset_dir(dataset), nfeature, latent_dim, k)

